import { collection, query, where, orderBy, getDocs, addDoc, updateDoc, deleteDoc, doc, limit } from "https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.11.0/firebase-auth.js";
import "./firebase-init.js";

const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const parseDate=s=>{const [y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)};
const formatDate=(s,o={day:"2-digit",month:"long",year:"numeric"})=>parseDate(s).toLocaleDateString("pt-BR",o);
const escapeHTML=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
window.todayKey=todayKey; window.parseDate=parseDate; window.formatDate=formatDate; window.escapeHTML=escapeHTML;
const col=(name)=>collection(window.firebaseDB,name);
async function getMine(name, ...constraints) {
  const q=query(col(name),where("user_id","==",window.firebaseAuth.currentUser.uid),...constraints);
  const snap=await getDocs(q); return snap.docs.map(d=>({id:d.id,...d.data()}));
}
window.dbAPI={col,getMine,add:(n,data)=>addDoc(col(n),data),update:(n,id,data)=>updateDoc(doc(window.firebaseDB,n,id),data),remove:(n,id)=>deleteDoc(doc(window.firebaseDB,n,id))};
async function requestNotifications(){if(!("Notification"in window))return alert("Seu navegador não oferece notificações.");const p=await Notification.requestPermission();if(p==="granted")new Notification("Meu Organizador ✨",{body:"Notificações ativadas!"})}
function setupCommon(){document.getElementById("themeBtn")?.addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem("theme",document.body.classList.contains("dark")?"dark":"light")});if(localStorage.getItem("theme")==="dark")document.body.classList.add("dark");document.getElementById("mobileMenu")?.addEventListener("click",()=>document.querySelector(".sidebar")?.classList.toggle("open"));document.getElementById("notificationBtn")?.addEventListener("click",requestNotifications);document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest(".modal").classList.add("hidden"))}
window.setupCommon=setupCommon;
async function loadHome(){const user=window.firebaseAuth.currentUser;if(!user)return;const tasks=await getMine("tasks",where("date","==",todayKey()),orderBy("time","asc"));const events=await getMine("events",where("date","==",todayKey()),orderBy("time","asc"));const exams=await getMine("exams",where("date",">=",todayKey()),orderBy("date","asc"),limit(4));const done=tasks.filter(t=>t.done).length;document.getElementById("todayLabel").textContent=new Date().toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long"});document.getElementById("heroDate").textContent=formatDate(todayKey(),{weekday:"long",day:"numeric",month:"long"});document.getElementById("totalTasks").textContent=tasks.length;document.getElementById("doneTasks").textContent=done;document.getElementById("eventCount").textContent=events.length;document.getElementById("progressValue").textContent=(tasks.length?Math.round(done/tasks.length*100):0)+"%";document.getElementById("taskList").innerHTML=tasks.map(t=>`<div class="task-item"><input class="task-check" type="checkbox" ${t.done?"checked":""} data-task="${t.id}"><div class="task-info"><div class="task-title ${t.done?"done":""}">${escapeHTML(t.title)}</div><div class="task-meta">${t.time||"Sem horário"} · ${escapeHTML(t.category)}</div></div><span class="priority ${t.priority}">${t.priority}</span><button class="delete-btn" data-del-task="${t.id}">×</button></div>`).join("");document.getElementById("emptyTasks").style.display=tasks.length?"none":"block";document.getElementById("todayEvents").innerHTML=events.map(e=>`<div class="event-item"><div class="event-time">${e.time||"Sem horário"} · ${escapeHTML(e.category)}</div><div class="event-title">${escapeHTML(e.title)}</div></div>`).join("");document.getElementById("emptyEvents").style.display=events.length?"none":"block";document.getElementById("upcomingExams").innerHTML=exams.map(e=>`<div class="exam-mini"><div class="exam-date"><strong>${parseDate(e.date).getDate()}</strong><small>${parseDate(e.date).toLocaleDateString("pt-BR",{month:"short"})}</small></div><div class="exam-mini-info"><strong>${escapeHTML(e.subject)}</strong><small>Prova · ${e.difficulty}</small></div></div>`).join("")||'<div class="empty-state">Cadastre uma prova na aba Estudos.</div>';document.getElementById("studyCount").textContent=0;document.querySelectorAll("[data-task]").forEach(c=>c.onchange=async()=>{await dbAPI.update("tasks",c.dataset.task,{done:c.checked});loadHome()});document.querySelectorAll("[data-del-task]").forEach(b=>b.onclick=async()=>{await dbAPI.remove("tasks",b.dataset.delTask);loadHome()})}
async function initHome(){setupCommon();await loadHome();document.getElementById("addTaskBtn").onclick=()=>modal.classList.remove("hidden");document.getElementById("taskForm").onsubmit=async e=>{e.preventDefault();const u=window.firebaseAuth.currentUser;await dbAPI.add("tasks",{user_id:u.uid,title:taskTitle.value,time:taskTime.value||null,priority:taskPriority.value,category:taskCategory.value,notes:taskNotes.value,date:todayKey(),done:false,created_at:new Date().toISOString()});modal.classList.add("hidden");e.target.reset();loadHome()}} 
onAuthStateChanged(window.firebaseAuth,user=>{if(user&&(location.pathname.endsWith("index.html")||location.pathname.endsWith("/")))setTimeout(initHome,100)});
