let calDate=new Date(), selectedDate=todayKey();
function renderCalendar(){
 const db=getDB(), y=calDate.getFullYear(),m=calDate.getMonth(), first=new Date(y,m,1), start=new Date(y,m,1-first.getDay()), days=new Date(y,m+1,0).getDate();
 document.getElementById("monthTitle").textContent=new Date(y,m,1).toLocaleDateString("pt-BR",{month:"long",year:"numeric"});
 const grid=document.getElementById("calendarGrid");grid.innerHTML="";
 for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=dateKey(d), inMonth=d.getMonth()===m, events=db.events.filter(e=>e.date===key), tasks=db.tasks.filter(e=>e.date===key);const cell=document.createElement("div");cell.className=`calendar-cell ${inMonth?"":"muted"} ${key===selectedDate?"selected":""}`;cell.innerHTML=`<div class="day-number">${key===todayKey()?`<span class="today-dot">${d.getDate()}</span>`:d.getDate()}</div>${events.slice(0,3).map(e=>`<span class="event-dot">• ${escapeHTML(e.title)}</span>`).join("")}${tasks.length?`<span class="event-dot">✓ ${tasks.length} tarefa(s)</span>`:""}`;cell.onclick=()=>{selectedDate=key;renderCalendar();renderSelected()};grid.appendChild(cell)}
}
function renderSelected(){
 const db=getDB(),events=db.events.filter(e=>e.date===selectedDate).sort((a,b)=>(a.time||"99").localeCompare(b.time||"99")),tasks=db.tasks.filter(e=>e.date===selectedDate);
 document.getElementById("selectedDateTitle").textContent=formatDate(selectedDate,{weekday:"long",day:"numeric",month:"long"});
 const box=document.getElementById("selectedEvents");box.innerHTML=[...events.map(e=>`<div class="event-item" style="margin-bottom:8px"><div class="event-time">${e.time||"Sem horário"} · ${escapeHTML(e.category)}</div><div class="event-title">${escapeHTML(e.title)}</div>${e.notes?`<div class="task-meta">${escapeHTML(e.notes)}</div>`:""}<button class="delete-btn" data-event-delete="${e.id}">Excluir</button></div>`),...tasks.map(t=>`<div class="event-item" style="margin-bottom:8px;border-left-color:#9b8ffb"><div class="event-time">TAREFA · ${t.time||"Sem horário"}</div><div class="event-title">${escapeHTML(t.title)}</div></div>`)].join("");
 document.getElementById("emptySelected").style.display=(events.length||tasks.length)?"none":"block";
 box.querySelectorAll("[data-event-delete]").forEach(b=>b.onclick=()=>{const d=getDB();d.events=d.events.filter(x=>x.id!==b.dataset.eventDelete);saveDB(d);renderCalendar();renderSelected()});
}
function initCalendar(){setupCommon();renderCalendar();renderSelected();document.getElementById("prevMonth").onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()};document.getElementById("nextMonth").onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()};document.getElementById("goToday").onclick=()=>{calDate=new Date();selectedDate=todayKey();renderCalendar();renderSelected()};document.getElementById("addEventBtn").onclick=()=>{eventForm.reset();eventDate.value=selectedDate;modal.classList.remove("hidden")};document.getElementById("eventForm").onsubmit=e=>{e.preventDefault();const d=getDB();d.events.push({id:uid(),title:eventTitle.value,date:eventDate.value,time:eventTime.value,category:eventCategory.value,notes:eventNotes.value});saveDB(d);selectedDate=eventDate.value;modal.classList.add("hidden");renderCalendar();renderSelected()}}
if(location.pathname.endsWith("calendario.html"))initCalendar();
