import { auth, db } from "./firebase-init.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { collection, query, orderBy, getDocs, addDoc, deleteDoc, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";

const grid=document.getElementById("calendarGrid"),title=document.getElementById("monthTitle"),selectedTitle=document.getElementById("selectedDateTitle"),selectedBox=document.getElementById("selectedEvents"),empty=document.getElementById("emptySelected"),modal=document.getElementById("modal"),form=document.getElementById("eventForm");
let user=null,current=new Date(),selected=iso(new Date()),events=[];
const months=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function br(s){const[y,m,d]=s.split("-");return `${d}/${m}/${y}`;}
function esc(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
async function load(){const s=await getDocs(query(collection(db,"users",user.uid,"events"),orderBy("date","asc"),orderBy("time","asc")));events=s.docs.map(x=>({id:x.id,...x.data()}));render();renderSelected();}
function render(){const y=current.getFullYear(),m=current.getMonth(),first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate();title.textContent=`${months[m]} ${y}`;grid.innerHTML="";for(let i=first-1;i>=0;i--)cell(new Date(y,m-1,prev-i),true);for(let d=1;d<=last;d++)cell(new Date(y,m,d),false);const rem=(first+last)%7?7-((first+last)%7):0;for(let d=1;d<=rem;d++)cell(new Date(y,m+1,d),true);}
function cell(d,muted){const key=iso(d),el=document.createElement("div");el.className=`calendar-cell${muted?" muted":""}${key===selected?" selected":""}`;el.innerHTML=`<div class="day-number">${key===iso(new Date())?`<span class="today-dot">${d.getDate()}</span>`:d.getDate()}</div>`;events.filter(e=>e.date===key).slice(0,3).forEach(e=>{const s=document.createElement("span");s.className="event-dot";s.textContent=`${e.time?e.time+" • ":""}${e.title}`;el.appendChild(s)});el.onclick=()=>{selected=key;document.getElementById("eventDate").value=selected;render();renderSelected();};grid.appendChild(el);}
function renderSelected(){selectedTitle.textContent=br(selected);selectedBox.innerHTML="";const arr=events.filter(e=>e.date===selected).sort((a,b)=>(a.time||"").localeCompare(b.time||""));empty.style.display=arr.length?"none":"block";arr.forEach(e=>{const el=document.createElement("div");el.className="event-item";el.innerHTML=`<div class="event-time">${esc(e.time||"Sem horário")}</div><div class="event-title">${esc(e.title)}</div><div class="task-meta">${esc(e.category||"Outro")}</div>${e.notes?`<div class="task-meta">${esc(e.notes)}</div>`:""}<button class="delete-btn">Excluir</button>`;el.querySelector("button").onclick=async()=>{if(confirm("Excluir este compromisso?")){await deleteDoc(doc(db,"users",user.uid,"events",e.id));load();}};selectedBox.appendChild(el);});}
document.getElementById("prevMonth")?.addEventListener("click",()=>{current.setMonth(current.getMonth()-1);render();});document.getElementById("nextMonth")?.addEventListener("click",()=>{current.setMonth(current.getMonth()+1);render();});document.getElementById("goToday")?.addEventListener("click",()=>{current=new Date();selected=iso(new Date());render();renderSelected();});document.getElementById("addEventBtn")?.addEventListener("click",()=>{document.getElementById("eventDate").value=selected;modal.classList.remove("hidden")});form?.addEventListener("submit",async e=>{e.preventDefault();const data={title:document.getElementById("eventTitle").value.trim(),date:document.getElementById("eventDate").value,time:document.getElementById("eventTime").value||"",category:document.getElementById("eventCategory").value,notes:document.getElementById("eventNotes").value.trim(),createdAt:serverTimestamp()};await addDoc(collection(db,"users",user.uid,"events"),data);selected=data.date;form.reset();modal.classList.add("hidden");load();});onAuthStateChanged(auth,u=>{if(u){user=u;document.getElementById("eventDate").value=selected;load();}});
