function studyStart(examDate,difficulty){const days=difficulty==="dificil"?25:difficulty==="facil"?15:18;const d=parseDate(examDate);d.setDate(d.getDate()-days);return d}
function generateSessions(exam){const start=studyStart(exam.date,exam.difficulty), end=parseDate(exam.date), arr=[], topics=exam.topics||"conteúdo da matéria";const total=Math.max(1,Math.round((end-start)/86400000));const phases=exam.difficulty==="dificil"?["Teoria e resumo","Exercícios","Exercícios + revisão","Prova antiga","Revisão final"]:["Teoria e resumo","Exercícios","Revisão","Simulado"];
 for(let i=0;i<=total;i++){const d=new Date(start);d.setDate(d.getDate()+i);if([0,6].includes(d.getDay()))continue;let phase=phases[Math.min(phases.length-1,Math.floor(i/Math.max(1,total/phases.length)))];arr.push({id:`${exam.id}_${dateKey(d)}`,examId:exam.id,date:dateKey(d),title:`${phase} — ${exam.subject}`,notes:topics})}
 return arr}
function allSessions(){return getDB().exams.flatMap(generateSessions).sort((a,b)=>a.date.localeCompare(b.date))}
function renderStudies(){
 const db=getDB(), exams=[...db.exams].sort((a,b)=>a.date.localeCompare(b.date)), today=todayKey(), sessions=allSessions();
 document.getElementById("examList").innerHTML=exams.map(e=>{const start=studyStart(e.date,e.difficulty),days=Math.ceil((parseDate(e.date)-new Date())/86400000);return `<div class="exam-card"><div><strong>${escapeHTML(e.subject)}</strong><br><small>Prova: ${formatDate(e.date)} · ${escapeHTML(e.difficulty)}</small><br><small>Começar: ${formatDate(dateKey(start))} · ${days>=0?days+" dias restantes": "já passou"}</small></div><button class="delete-btn" data-exam="${e.id}">×</button></div>`}).join("");document.getElementById("emptyExams").style.display=exams.length?"none":"block";
 const sel=document.getElementById("studyFilter"), old=sel.value;sel.innerHTML=`<option value="all">Todas as provas</option>`+exams.map(e=>`<option value="${e.id}">${escapeHTML(e.subject)}</option>`).join("");sel.value=exams.some(e=>e.id===old)?old:"all";
 const filtered=sel.value==="all"?sessions:sessions.filter(s=>s.examId===sel.value);
 const grouped={};filtered.forEach(s=>(grouped[s.date]??=[]).push(s));
 document.getElementById("studySchedule").innerHTML=Object.entries(grouped).map(([date,ss])=>`<div class="schedule-day"><div class="schedule-date">${formatDate(date,{weekday:"long",day:"numeric",month:"long"})}</div>${ss.map(s=>`<label class="schedule-task"><input type="checkbox" ${db.studyDone[s.id]?"checked":""} data-study="${s.id}"><span>${escapeHTML(s.title)}</span></label>`).join("")}</div>`).join("")||`<div class="empty-state">Nenhuma sessão encontrada.</div>`;
 const today=sessions.filter(s=>s.date===today);document.getElementById("studyToday").innerHTML=today.map(s=>`<label class="schedule-task"><input type="checkbox" ${db.studyDone[s.id]?"checked":""} data-study="${s.id}"><span>${escapeHTML(s.title)}</span></label>`).join("");document.getElementById("emptyStudyToday").style.display=today.length?"none":"block";
 document.querySelectorAll("[data-study]").forEach(c=>c.onchange=()=>{const d=getDB();if(c.checked)d.studyDone[c.dataset.study]=true;else delete d.studyDone[c.dataset.study];saveDB(d);renderStudies()});
 document.querySelectorAll("[data-exam]").forEach(b=>b.onclick=()=>{if(confirm("Excluir esta prova e o cronograma gerado?")){const d=getDB();d.exams=d.exams.filter(e=>e.id!==b.dataset.exam);Object.keys(d.studyDone).filter(k=>k.startsWith(b.dataset.exam+"_")).forEach(k=>delete d.studyDone[k]);saveDB(d);renderStudies()}});
}
function initStudies(){setupCommon();renderStudies();document.getElementById("studyFilter").onchange=renderStudies;document.getElementById("addExamBtn").onclick=()=>{examForm.reset();modal.classList.remove("hidden")};document.getElementById("examForm").onsubmit=e=>{e.preventDefault();const d=getDB();d.exams.push({id:uid(),subject:examSubject.value,date:examDate.value,difficulty:examDifficulty.value,topics:examTopics.value});saveDB(d);modal.classList.add("hidden");renderStudies()}}
if(location.pathname.endsWith("estudos.html"))initStudies();
