import { auth, db } from "./firebase-init.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { collection, query, orderBy, getDocs, addDoc, doc, updateDoc, writeBatch, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";

const modal=document.getElementById("modal"),form=document.getElementById("examForm"),examList=document.getElementById("examList"),emptyExams=document.getElementById("emptyExams"),studyToday=document.getElementById("studyToday"),emptyToday=document.getElementById("emptyStudyToday"),schedule=document.getElementById("studySchedule"),filter=document.getElementById("studyFilter");
let user=null,exams=[],sessions=[];
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function parse(s){const[y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d);}
function br(s){const[y,m,d]=s.split("-");return `${d}/${m}/${y}`;}
function esc(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function startDate(date,diff){const days=diff==="facil"?15:diff==="dificil"?21:18,d=parse(date);d.setDate(d.getDate()-days);return d;}
function topics(raw){const a=(raw||"").split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean);return a.length?a:["Conteúdo geral da prova"]; }
function generate(exam){const start=startDate(exam.date,exam.difficulty),end=parse(exam.date),ts=topics(exam.topics),days=[];for(let d=new Date(start);d<end;d.setDate(d.getDate()+1)){if([1,2,4,5].includes(d.getDay()))days.push(new Date(d));}return days.map((d,i)=>{const p=days.length<=1?1:i/(days.length-1);let phase="Teoria e compreensão";if(p>=.35&&p<.7)phase="Exercícios e fixação";if(p>=.7&&p<.9)phase="Revisão + questões";if(p>=.9)phase="Revisão final";return{examId:exam.id,subject:exam.subject,date:iso(d),phase,topic:p>=.9?"Revisão geral da prova":ts[i%ts.length],done:false,createdAt:serverTimestamp()};});}
async function load(){const[es,ss]=await Promise.all([getDocs(query(collection(db,"users",user.uid,"exams"),orderBy("date","asc"))),getDocs(query(collection(db,"users",user.uid,"studySessions"),orderBy("date","asc")))]);exams=es.docs.map(x=>({id:x.id,...x.data()}));sessions=ss.docs.map(x=>({id:x.id,...x.data()}));renderExams();renderFilter();renderSchedule();renderToday();}
function renderExams(){examList.innerHTML="";emptyExams.style.display=exams.length?"none":"block";exams.forEach(e=>{const card=document.createElement("div");card.className="exam-card";card.innerHTML=`<div><strong>${esc(e.subject)}</strong><div><small>Prova: ${br(e.date)} • ${e.difficulty}</small></div><div><small>Começar: ${br(iso(startDate(e.date,e.difficulty)))}</small></div></div><button class="delete-btn">×</button>`;card.querySelector("button").onclick=async()=>{if(!confirm(`Excluir a prova de ${e.subject} e o cronograma?`))return;const batch=writeBatch(db);batch.delete(doc(db,"users",user.uid,"exams",e.id));sessions.filter(s=>s.examId===e.id).forEach(s=>batch.delete(doc(db,"users",user.uid,"studySessions",s.id)));await batch.commit();load();};examList.appendChild(card);});}
function renderFilter(){const old=filter.value;filter.innerHTML='<option value="all">Todas as provas</option>';exams.forEach(e=>{const o=document.createElement("option");o.value=e.id;o.textContent=e.subject;filter.appendChild(o)});filter.value=exams.some(e=>e.id===old)?old:"all";}
function row(s){const r=document.createElement("label");r.className="schedule-task";r.innerHTML=`<input type="checkbox" ${s.done?"checked":""}><span><strong>${esc(s.subject)}</strong> — ${esc(s.phase)}: ${esc(s.topic)}</span>`;r.querySelector("input").onchange=async ev=>{await updateDoc(doc(db,"users",user.uid,"studySessions",s.id),{done:ev.target.checked});s.done=ev.target.checked;renderToday();};return r;}
function renderSchedule(){const arr=filter.value==="all"?sessions:sessions.filter(s=>s.examId===filter.value),groups=new Map();schedule.innerHTML="";if(!arr.length){schedule.innerHTML='<div class="empty-state">Nenhuma sessão programada.</div>';return;}arr.forEach(s=>{if(!groups.has(s.date))groups.set(s.date,[]);groups.get(s.date).push(s)});for(const[d,a]of groups){const b=document.createElement("div");b.className="schedule-day";b.innerHTML=`<div class="schedule-date">${br(d)}</div>`;a.forEach(s=>b.appendChild(row(s)));schedule.appendChild(b);}}
function renderToday(){const arr=sessions.filter(s=>s.date===iso(new Date()));studyToday.innerHTML="";emptyToday.style.display=arr.length?"none":"block";arr.forEach(s=>studyToday.appendChild(row(s)));}
document.getElementById("addExamBtn")?.addEventListener("click",()=>{form.reset();modal.classList.remove("hidden")});filter?.addEventListener("change",renderSchedule);form?.addEventListener("submit",async ev=>{ev.preventDefault();const exam={subject:document.getElementById("examSubject").value.trim(),date:document.getElementById("examDate").value,difficulty:document.getElementById("examDifficulty").value,topics:document.getElementById("examTopics").value.trim(),createdAt:serverTimestamp()};const ref=await addDoc(collection(db,"users",user.uid,"exams"),exam),plan=generate({...exam,id:ref.id}),batch=writeBatch(db);plan.forEach(s=>batch.set(doc(collection(db,"users",user.uid,"studySessions")),s));await batch.commit();form.reset();modal.classList.add("hidden");load();});onAuthStateChanged(auth,u=>{if(u){user=u;load();}});
