import { auth, db } from "./firebase-init.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { collection, query, orderBy, getDocs, addDoc, deleteDoc, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";

const modal=document.getElementById("modal"),form=document.getElementById("projectForm"),grid=document.getElementById("projectGrid"),empty=document.getElementById("emptyProjects");let user=null;
function esc(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function br(s){if(!s)return"";const[y,m,d]=s.split("-");return `${d}/${m}/${y}`;}
async function load(){const s=await getDocs(query(collection(db,"users",user.uid,"projects"),orderBy("createdAt","desc")));grid.innerHTML="";empty.style.display=s.empty?"block":"none";s.forEach(x=>{const p=x.data(),card=document.createElement("article");card.className=`project-card ${p.color||"purple"}`;card.innerHTML=`<h3>${esc(p.name)}</h3><p>${esc(p.description||"Sem descrição.")}</p><div class="project-deadline">${p.deadline?`Prazo: ${br(p.deadline)}`:"Sem prazo definido"}</div><button class="delete-btn">Excluir</button>`;card.querySelector("button").onclick=async()=>{if(confirm(`Excluir o projeto "${p.name}"?`)){await deleteDoc(doc(db,"users",user.uid,"projects",x.id));load();}};grid.appendChild(card);});}
document.getElementById("addProjectBtn")?.addEventListener("click",()=>{form.reset();modal.classList.remove("hidden")});form?.addEventListener("submit",async e=>{e.preventDefault();await addDoc(collection(db,"users",user.uid,"projects"),{name:document.getElementById("projectName").value.trim(),description:document.getElementById("projectDescription").value.trim(),color:document.getElementById("projectColor").value,deadline:document.getElementById("projectDeadline").value||"",createdAt:serverTimestamp()});form.reset();modal.classList.add("hidden");load();});onAuthStateChanged(auth,u=>{if(u){user=u;load();}});
